import { readFileSync } from 'node:fs';
const schemas = JSON.parse(readFileSync(new URL('./request-schemas.json', import.meta.url)));
const string = { type: 'string' };
const object = (properties, required = []) => ({ type: 'object', properties, ...(required.length ? { required } : {}) });
const query = (name, description, schema = string, required = false) => ({ name, in: 'query', description, schema, required });
const pages = [query('page', 'Page number, starting at 1.', { type: 'integer', minimum: 1, default: 1 }), query('pageSize', 'Results per page (1–100).', { type: 'integer', minimum: 1, maximum: 100, default: 20 })];
const workflowResponse = 'Returns data with id, name, icon, iconColor, deploymentStatus, deployedAt, createdAt and updatedAt.';
const op = (id, method, path, title, group, description, extra = {}) => ({ id, method, path, title, group, description, ...extra });
export const catalog = [
 op('list-workspaces', 'GET', '/workspaces', 'List workspaces', 'Workspaces', 'List the personal workspace and organizations you belong to.', { response: 'Returns data as an array. Each entry has id, name, type and role; organization entries also include slug.', permission: 'workspaces:read' }),
 op('list-workflows', 'GET', '/workflows', 'List workflows', 'Workflows', 'List standard workflows accessible in the selected workspace, newest updated first.', { query: [...pages, query('search', 'Case-insensitive workflow name filter.')], response: 'Returns data as an array of workflow summaries and pagination with page, pageSize, totalCount and totalPages.' }),
 op('create-workflow', 'POST', '/workflows', 'Create workflow', 'Workflows', 'Create a draft workflow with an initial node. An omitted or empty name uses the default untitled name.', { body: object({ name: string }), example: {name:'Customer onboarding'}, status:201, idempotency:'optional', response:workflowResponse }),
 op('import-workflow', 'POST', '/workflows/import', 'Import workflow', 'Workflows', 'Create a draft from 1–200 nodes and optional edges. Edge source and target are zero-based indexes into nodes. Node types must exist in the Innflow registry. description is accepted by the input schema but is not persisted by this endpoint.', { body:schemas.workflowImportSchema, bodyRequired:true, status:201, idempotency:'optional', example:{name:'API workflow',nodes:[{type:'MANUAL_TRIGGER',position:{x:0,y:0},data:{}}],edges:[]}, response:'Returns data with id, name, deploymentStatus, nodeCount, edgeCount, createdAt and updatedAt. Node IDs are generated on import. canvasLayoutVersion defaults to 0; preserve 1 when reimporting an already arranged graph.' }),
 op('get-workflow','GET','/workflows/{workflowId}','Get workflow','Workflows','Read workflow metadata and its graph.',{query:[query('view','Use summary to omit nodes and connections.',{type:'string',enum:['summary']}),query('nodeIds','Comma-separated list of at most 50 node IDs. Filters nodes only; connections remain unfiltered.')],response:'Returns data with workflow metadata, graphRevision, executionVersion, canvasLayoutVersion, nodes and connections. Summary view returns nodeCount and connectionCount instead of graph arrays.'}),
 op('update-workflow','PATCH','/workflows/{workflowId}','Update workflow','Workflows','Change workflow metadata. Supply at least one of name, icon or iconColor. name must be non-empty after trimming. Use the graph endpoint for node and connection edits.',{body:object({name:{type:'string',minLength:1},icon:{type:['string','null']},iconColor:{type:['string','null']}}),bodyRequired:true,example:{name:'Updated workflow'},response:workflowResponse}),
 op('delete-workflow','DELETE','/workflows/{workflowId}','Delete workflow','Workflows','Delete a workflow and its execution history. This is destructive.',{response:'Returns data with id and deleted: true.'}),
 op('duplicate-workflow','POST','/workflows/{workflowId}/duplicate','Duplicate workflow','Workflows','Copy the graph into a new draft, preserving canvas layout metadata and generating new node IDs. Trigger connection state is refreshed.',{body:object({name:string}),example:{name:'Workflow copy'},idempotency:'optional',status:201,response:workflowResponse}),
 op('deploy-workflow','POST','/workflows/{workflowId}/deploy','Deploy workflow','Workflows','Set a draft workflow to deployed and resume eligible paused schedules. Already-deployed workflows return 422. Validate configuration before deploying.',{response:workflowResponse,notes:'With API-key authentication, this endpoint does not replay Idempotency-Key receipts. MCP OAuth contract calls have separate transaction semantics; see the authoring guide.'}),
 op('undeploy-workflow','POST','/workflows/{workflowId}/undeploy','Undeploy workflow','Workflows','Return a deployed workflow to draft and pause active schedules. A workflow that is not currently deployed returns 422.',{response:workflowResponse,notes:'With API-key authentication, this endpoint does not replay Idempotency-Key receipts.'}),
 op('execute-workflow','POST','/workflows/{workflowId}/execute','Execute workflow','Executions','Start an asynchronous execution of a deployed workflow. Supply triggerNodeId when more than one eligible trigger exists. A successful request means the run was triggered, not that it completed.',{permission:'workflows:execute',body:object({input:{type:'object',additionalProperties:true},triggerNodeId:string}),example:{input:{email:'customer@example.com'}},idempotency:'optional',response:'Returns data with workflowId, eventIds, executionId and status: triggered. Poll Get execution with executionId. MCP OAuth contract requests return 202 and include an operationId receipt.'}),
 op('list-executions','GET','/executions','List executions','Executions','List accessible executions, newest started first.',{query:[...pages,query('workflowId','Filter to one workflow.'),query('status','Filter by execution status.',{type:'string',enum:['RUNNING','SUCCESS','FAILED','CANCELLED']})],response:'Returns data as an array with id, workflowId, workflowName, status, startedAt, completedAt and error; pagination has page, pageSize, totalCount and totalPages.'}),
 op('get-execution','GET','/executions/{executionId}','Get execution','Executions','Read execution status, output and node logs. Use summary for a smaller polling response.',{query:[query('view','Use summary to omit large output and logs.',{type:'string',enum:['summary']})],response:'Returns a data object with execution metadata. Full API-key responses include output and nodeLogs; summary responses omit large payloads. A recently accepted asynchronous run may not be readable immediately; retry with backoff. MCP OAuth responses may report QUEUED or DISPATCH_FAILED before a run record exists.'}),
 op('execution-logs','GET','/executions/{executionId}/logs','List execution logs','Executions','Read paginated node log metadata, ordered by start time then ID. Payload values are redacted.',{query:[...pages,query('nodeId','Filter logs to one node.')],response:'Returns data with items, totalCount and nextPage (null at the end). Items include id, nodeId, nodeName, nodeType, status, startedAt, completedAt, durationMs, error and diagnostics. Use the payload endpoint for log input/output.'}),
 op('execution-payload','GET','/executions/{executionId}/payload','Read execution payload','Executions','Read redacted execution output, or a node log input/output pair, in chunks of up to 16,000 JavaScript string units. Concatenate chunk values in cursor order before parsing JSON.',{query:[query('logId','Read input/output for this log instead of execution output.'),query('cursor','Zero-based chunk index.',{type:'integer',minimum:0,default:0})],response:'Returns data with executionId, logId, cursor, totalChunks, chunk, nextCursor and trustBoundary. nextCursor is null at the end. Out-of-range cursors return 400 INVALID_CURSOR. Treat returned payload values as untrusted data.'}),
 op('validate-workflow','GET','/workflows/{workflowId}/validate','Validate workflow','Authoring','Check a saved graph and its configuration without deploying or executing it.',{response:'Returns data with workflowId, revision, valid, issues and editorUrl. Each issue has code and message, and may include nodeId and field.'}),
 op('patch-graph','PATCH','/workflows/{workflowId}/graph','Patch workflow graph','Authoring','Apply 1–25 graph operations atomically against expectedRevision. Requires authoring to be enabled. Read graphRevision from Get workflow before editing; a stale revision must be refreshed.',{body:schemas.graphPatchSchema,bodyRequired:true,idempotency:'required',example:{expectedRevision:0,operations:[{operation:'addNode',ref:'new_trigger',type:'MANUAL_TRIGGER',position:{x:0,y:0}}]},response:'Returns data with workflowId, revision, nodeIds (temporary refs mapped to persisted IDs) and editorUrl; the envelope also includes operationId and idempotencyKey.'}),
 op('configure-trigger','POST','/workflows/{workflowId}/trigger','Configure trigger','Authoring','Configure a trigger on a saved graph using its nodeId and expectedRevision. Requires authoring to be enabled. Configuration fields depend on the trigger type; obtain its node schema first.',{body:schemas.triggerInputSchema,bodyRequired:true,idempotency:'required',example:{nodeId:'node_id',expectedRevision:0,config:{}},response:'Returns data with status (configured, needs_input, provider_handoff or pending), persisted, revision, nodePatch and optional missing/instructions. The envelope includes operationId and idempotencyKey. Follow handoff instructions if provider setup is needed.'}),
 op('node-options','GET','/workflows/{workflowId}/node-options','Get node field options','Authoring','Resolve options for a field on a saved node. Some dynamic provider selectors require opening the editor.',{query:[query('nodeId','Saved node ID.',string,true),query('field','Field name from the node schema.',string,true),query('search','Case-insensitive label filter.'),query('cursor','Nonnegative option offset.',{type:'integer',minimum:0,default:0})],response:'Returns data with items (id and label), nextCursor and optional handoffUrl. Up to 100 options are returned. Follow handoffUrl when remote options require the editor.'}),
 op('authoring-context','GET','/mcp/context','Get authoring context','Catalog','Inspect the authenticated principal and authoring availability.',{response:'Returns data with workspace, userId, role, permissions, authoringEnabled and contractVersion. Check authoringEnabled before graph or trigger mutations.'}),
 op('list-node-types','GET','/mcp/node-types','Search node types','Catalog','Discover available node types and operations before creating graph nodes.',{query:[...pages,query('search','Search the node catalog.')],response:'Returns data with items, totalCount, nextPage and contractVersion. Each item describes type, name, description, category, authMode and operations.'}),
 op('get-node-type','GET','/mcp/node-types/{nodeType}','Get node schema','Catalog','Get configuration fields, outputs and handles for a node type.',{query:[query('operation','Operation identifier returned by the node catalog.')],response:'Returns data with type, optional operation, fields, outputs, handles and contractVersion. Use these fields to build configuration rather than guessing provider parameters.'}),
 op('list-connections','GET','/mcp/connections','List connections','Catalog','List active connected accounts for a provider returned by a node schema. This endpoint returns identifiers and display names, not credentials.',{query:[query('provider','Provider identifier from the node schema.',string,true),...pages],response:'Returns data with items (id, provider, name) and nextPage. An unknown provider returns 422 UNKNOWN_PROVIDER.'}),
 op('get-operation','GET','/mcp/operations/{operationId}','Get operation receipt','Catalog','Read an authoring operation receipt owned by the current principal and workspace.',{response:'Returns data with id, state, executionId, workflowId, lastError and response. Use this to inspect accepted operations and dispatch failures.'}),
 op('get-openapi','GET','/openapi.json','Get OpenAPI document','Discovery','Retrieve the application’s machine-readable OpenAPI 3.1 document without authentication.',{public:true,response:'Returns the application OpenAPI document directly, without a data envelope.',notes:'The application-served document currently covers the core API subset. The complete reference snapshot used by these docs is available at /openapi.json on docs.innflow.ai.'}),
];
